language: java
script: mvn install -DskipTests=true -P strict
after_success:
  - mvn clean cobertura:cobertura coveralls:report
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
branches:
  only:
  - master
